title: Peter Stahr
description: Interactive Media Designer
site_title: '@pstahr - Peter Stahr'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: stahrp
blog_url: https://www.pstahr.com
email: stahrp04@gmail.com
linkedin: https://www.linkedin.com/in/peter-stahr/
resume_pdf: 
resume_docx: 
# keybase_username: abhn
# twitter_username: abhn_
# reddit_username: abhn

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
